user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
daemon off;

events {
	worker_connections 768;
}

http {
	sendfile on;
	tcp_nopush on;
	types_hash_max_size 2048;
	include /etc/nginx/mime.types;
	default_type application/octet-stream;
	access_log /dev/stdout;
	error_log /dev/stderr;
	gzip on;

    # INCREASE UPLOAD LIMIT DIRECTLY IN HTTP BLOCK
    client_max_body_size 500M;

	server {
		listen {{PORT}};
		server_name _;
		root {{NIXPACKS_PHP_ROOT_DIR}};

		add_header X-Frame-Options "SAMEORIGIN";
		add_header X-XSS-Protection "1; mode=block";
		add_header X-Content-Type-Options "nosniff";

		index index.html index.htm index.php;

		charset utf-8;

		location / {
			try_files $uri $uri/ /index.php?$query_string;
		}

		location = /favicon.ico { access_log off; log_not_found off; }
		location = /robots.txt  { access_log off; log_not_found off; }

		error_page 404 /index.php;

		location ~ \.php$ {
			fastcgi_pass {{NIXPACKS_PHP_FPM_ADDRESS}};
			fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
			include fastcgi_params;
			include fastcgi.conf;
			fastcgi_hide_header X-Powered-By;
		}

		location ~ /\.(?!well-known).* {
			deny all;
		}
	}
}
