[build]
builder = "nixpacks"

[deploy]
# We must use startCommand because the default Nixpacks web server doesn't boot Laravel properly without it.
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
